//! Keeps `web/dist` present and fresh for `rust-embed`.
//!
//! Two jobs:
//!
//! 1. **Seed.** `web/dist` is generated by `npm run build` in `web/` and is not
//!    tracked by git, so a clone without node has nothing for `rust-embed` to
//!    embed. When `web/dist/index.html` is missing, the committed
//!    `web/placeholder/index.html` is copied in so `cargo build` works on its
//!    own, and a marker is left beside it. A real vite build is never
//!    overwritten; a copy this script seeded earlier is refreshed, since
//!    `web/dist` survives every checkout and would otherwise pin the first
//!    placeholder a machine ever built with. Vite runs with `emptyOutDir`, so a
//!    real build clears the marker along with everything else.
//! 2. **Invalidate.** `rust-embed`'s `debug-embed` decides *when* assets are
//!    baked in, not when cargo reconsiders them: the proc macro cannot emit
//!    `cargo:rerun-if-changed`, so without this script a fresh `npm run build`
//!    followed by `cargo run` serves the previously embedded bytes.
//!
//! Directory `rerun-if-changed` tracks the directory's own mtime, which covers
//! files appearing and disappearing but not edits nested under `assets/`. Vite
//! rewrites `index.html` on every build, so that file is tracked by name too.
//!
//! It also points git at the repository's tracked hooks, because a check nobody
//! is made to run is a check that eventually does not run — see `install_hooks`.

use std::fs;
use std::path::Path;
use std::process::Command;

/// Point `core.hooksPath` at the tracked `.githooks/`, so a fresh clone picks
/// up the pre-commit guardrail on its first build.
///
/// Git does not clone hooks and will not run them from a tracked directory
/// without being told, so the alternative is a setup step in a README that
/// every new clone is free to skip. This is idempotent, touches only this
/// repository's local config, and is silently skipped when there is no `.git`
/// (a `cargo install` from a package, or a vendored copy) or when the hooks
/// directory is absent. It never fails the build: a missing guardrail is worth
/// a warning, not a broken `cargo build`.
fn install_hooks() {
    if !Path::new("../../.git").exists() || !Path::new("../../.githooks").is_dir() {
        return;
    }
    let current = Command::new("git")
        .args(["config", "--get", "core.hooksPath"])
        .output();
    if let Ok(out) = &current {
        if String::from_utf8_lossy(&out.stdout).trim() == ".githooks" {
            return;
        }
    }
    match Command::new("git")
        .args(["config", "core.hooksPath", ".githooks"])
        .status()
    {
        Ok(status) if status.success() => {}
        _ => println!(
            "cargo:warning=could not set core.hooksPath; run `git config core.hooksPath .githooks` \
             so the no-real-data check runs before each commit"
        ),
    }
}

fn main() {
    install_hooks();
    println!("cargo:rerun-if-changed=../../web/dist");
    println!("cargo:rerun-if-changed=../../web/dist/index.html");
    println!("cargo:rerun-if-changed=../../web/placeholder/index.html");

    let dist = Path::new("../../web/dist");
    let index = dist.join("index.html");
    let placeholder = Path::new("../../web/placeholder/index.html");

    if !placeholder.exists() {
        println!("cargo:warning=web/placeholder/index.html is missing; web/dist may be empty");
        return;
    }

    let marker = dist.join(".seeded-from-placeholder");
    if index.exists() && !marker.exists() {
        return;
    }

    let seeded = fs::create_dir_all(dist)
        .and_then(|()| fs::copy(placeholder, &index))
        .and_then(|_| {
            fs::write(
                &marker,
                "web/dist holds the placeholder, not a vite build\n",
            )
        });
    if let Err(err) = seeded {
        println!("cargo:warning=could not seed web/dist from the placeholder: {err}");
    }
}
